spring.application.name=ai-service

server.port=8084

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

ollama.url=${OLLAMA_URL}
ollama.model=${OLLAMA_MODEL}

image.service.url=${IMAGE_SERVICE_URL}